### ISSUE TITLE
Headline underline wraps oddly when page is sized down

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/documentcloud-notes#9]
When [this page](http://www.opb.org/news/article/earthquake-insurance-policy-coverage/) is sized down, the underline on the headline link gets pushed to the right.

Also, it might look better the wrapped headline's second line was flush left with the line above it.

![screen shot 2016-02-15 at 7 44 19 pm](https://cloud.githubusercontent.com/assets/273891/13064034/c5755308-d41c-11e5-8085-cd192244b021.png)

**Comment by reefdog** [comment]
Fixed in 221b5a82e007cf233ea5a7e2f13834801f54b542

**Comment by anthonydb** [comment]
Thanks!
